### ISSUE TITLE
constant panicing with chi v5 and pgxpool

### ISSUE THREAD

**Issue by c-nv-s** [alexedwards/scs#148] opened 2022-08-13 19:39 UTC
basic edited version of pgxpool example with chi v5 is constantly panicing:
```
package main

import (
	"context"
	"io"
	"log"
	"net/http"
	"time"

	"github.com/alexedwards/scs/pgxstore"
	"github.com/alexedwards/scs/v2"
	"github.com/go-chi/chi/middleware"
	chi "github.com/go-chi/chi/v5"
	"github.com/jackc/pgx/v4/pgxpool"
)

var sessionManager *scs.SessionManager

func main() {

	pool, err := pgxpool.Connect(context.Background(), "postgres://username:password@host/dbname")
	if err != nil {
		log.Fatal(err)
	}
	defer pool.Close()

	sessionManager := scs.New()
	sessionManager.Store = pgxstore.New(pool)
	sessionManager.Lifetime = 3 * time.Hour

	router := chi.NewRouter()
	router.Use(middleware.RequestID)
	router.Use(middleware.RealIP)
	router.Use(middleware.Logger)
	router.Use(middleware.Recoverer)
	router.Use(sessionManager.LoadAndSave) // THIS MUST BE USED LAST OTHERWISE WILL PANIC???
	router.Get("/put", putHandler)
	router.Get("/get", getHandler)
	http.ListenAndServe(":3000", router)

}

func putHandler(w http.ResponseWriter, r *http.Request) {
	sessionManager.Put(r.Context(), "message", "Hello from a session!")
}

func getHandler(w http.ResponseWriter, r *http.Request) {
	msg := sessionManager.GetString(r.Context(), "message")
	io.WriteString(w, msg)
}
```

**Comment by alexedwards** [comment] 2022-08-14 15:06
Hi,

The problem is this line in your code: 

```
sessionManager := scs.New()
```

By using `:=` you are creating and assigning to a `sessionManager` variable scoped to the `main()` function, not your `sessionManager` global variable. 

Please try changing it to the following instead:

```
sessionManager = scs.New()
```

**Closed by alexedwards** 2022-08-14 15:06 UTC
