### ISSUE TITLE
2.7.0 breaks websocket compatibility

### ISSUE THREAD

**Issue by shlomimatichin** [alexedwards/scs#196] opened 2024-02-02 23:14 UTC
this patch: https://github.com/alexedwards/scs/commit/62e546ce9d2d95a370da0629bd877d9e0c4ed9a0
removed the "Hijack" method, which is required to be able to escalate http 1.1 connection to websocket.
after upgrading, we now get: "websocket: response does not implement http.Hijacker", some googling relevant links:
https://stackoverflow.com/questions/62980183/response-does-not-implement-http-hijacker
we are downgrading for now.

**Comment by alexedwards** [comment] 2024-02-03 16:58
Dupe of https://github.com/alexedwards/scs/issues/188

**Closed by alexedwards** 2024-02-03 16:58 UTC

**Comment by alexedwards** [comment] 2024-02-03 17:48
See response in https://github.com/alexedwards/scs/issues/188#issuecomment-1925412377
