### ISSUE TITLE
Set lifetime per session

### ISSUE THREAD

**Issue by eduardhasanaj2** [alexedwards/scs#73] opened 2019-10-25 17:45 UTC
Hi,
I have been using scs for some time and it looks great.
I hava a concern why I cannot set lifetime per session.
Is there any worrkaround?

**Comment by alexedwards** [comment] 2019-10-25 20:45
Hi,

Do you mean so that one user has a shorter session lifetime (like one hour) and another user has a longer session lifetime (like one day), but while using the same `scs.SessionManager` instance?

If yes, could you describe the reason behind wanting to do this?

**Comment by eduardhasanaj2** [comment] 2019-10-25 21:09
Hi @alexedwards 
I want to have a remember me option and in this case the session lifetime can be up to 30 days.
In the other hand, when this option is unchecked, the session lifetime will be short. 
I do not want to create different instances of session manager as it makes it harder the session check.

**Comment by alexedwards** [comment] 2019-10-27 15:32
Thanks for confirming. I think this is a duplicate of https://github.com/alexedwards/scs/issues/71 so I'm going to close this one.

**Closed by alexedwards** 2019-10-27 15:32 UTC
